/** @format */

const USER_INFO = 'USER_INFO';
const TOKEN = 'TOKEN';
const USER_ACCOUNT = 'USER_ACCOUNT';
const LIST_STORAGE_ORG = 'LIST_STORAGE_ORG';
const LIST_ORG = 'LIST_ORG';
const APP_TOKEN = 'APP_TOKEN';
const TYPE_REGISTER_LEAVE = 'TYPE_REGISTER_LEAVE';
const TYPE_REGISTER_OT = 'TYPE_REGISTER_OT';
const TYPE_REGISTER_WLEO = 'TYPE_REGISTER_WLEO';
const NOTIFICATION = 'NOTIFICATION';
const APP_CONFIG = 'APP_CONFIG';
const BUSSINESS_CONFIG = 'BUSSINESS_CONFIG';
const FIRST_INIT_APP = 'FIRST_INIT_APP';
const APP_SETTINGS = 'APP_SETTINGS';
const APP_NAVIGATION = 'APP_NAVIGATION';
const LIST_PROVINCE = 'LIST_PROVINCE';
const LIST_EMP = 'LIST_EMP';

const LIST_RELATIONSHIP = 'LIST_RELATIONSHIP';
const LIST_GENDER = 'LIST_GENDER';
const LIST_NATION = 'LIST_NATION';
const MENU_DASHBOARD = 'MENU_DASHBOARD';
const THEMES = 'THEMES';


export {
	USER_INFO,
	TOKEN,
	USER_ACCOUNT,
	LIST_STORAGE_ORG,
	LIST_ORG,
	APP_TOKEN,
	TYPE_REGISTER_LEAVE,
	TYPE_REGISTER_OT,
	TYPE_REGISTER_WLEO,
	NOTIFICATION,
	APP_CONFIG,
	BUSSINESS_CONFIG,
	FIRST_INIT_APP,
	APP_SETTINGS,
	APP_NAVIGATION,
	LIST_PROVINCE,
	LIST_EMP,
	LIST_RELATIONSHIP,
	LIST_GENDER,
	LIST_NATION,
	MENU_DASHBOARD,
	THEMES,
};
