/** @format */

// leave off @2x/@3x
const images = {
	// logo: require('Images/histaff-logo.png'),
	// shortLogo: require('Images/Icons/short-logo.png'),
	// avatar: require('Images/avatar.png'),
	// uploadfile: require('Images/img_fileupload.png'),
	avatar_uri_default: 'https://www.w3schools.com/howto/img_avatar.png',
	backgroundImage: require('../Images/backgroundImage.png'),
	backgroundImageNew: require('../Images/backgroundImageNew.png'),
	logoHiStaff: require('../Images/logo_largest.png'),
	logoNew: require('../Images/logoNew.png'),
	userIcon: require('../Images/Icons/user.png'),
	passwordIcon: require('../Images/Icons/password.png'),
	eyeIcon: require('../Images/Icons/eye.png'),
	// clearLogo: require('Images/top_logo.png'),
	// launch: require('Images/launch-icon.png'),
	// ready: require('Images/your-app.png'),
	// ignite: require('Images/ignite_logo.png'),
	// igniteClear: require('Images/ignite-logo-transparent.png'),
	// tileBg: require('Images/tile_bg.png'),
	// background: require('Images/BG.png'),
	// buttonBackground: require('Images/button-bg.png'),
	// faq: require('Images/Icons/faq-icon.png'),
	// chevronRight: require('Images/Icons/chevron-right.png'),
	// hamburger: require('Images/Icons/hamburger.png'),
	// backButton: require('Images/Icons/back-button.png'),

	// registerLeave: require('Images/Icons/register-leave.png'),
	// approveLeave: require('Images/Icons/approve-leave.png'),
	// registerOT: require('Images/Icons/register-ot.png'),
	// event: require('Images/Icons/event.png'),
	// approveOT: require('Images/Icons/approve-ot.png'),
	// registerLateInEarlyOut: require('Images/Icons/register-late-in-early-out.png'),
	// approveLateInEarlyOut: require('Images/Icons/approve-late-in-early-out.png'),
	timesheets: require('../Images/Icons/timesheets.png'),
	salary: require('../Images/Icons/salary.png'),
	// Payroll_Timesheets: require('Images/Icons/Payroll_Timesheets.png'),
	home: require('../Images/Icons/home.png'),
	contacts: require('../Images/Icons/contacts.png'),
	compensationsAndBenefits: require('../Images/Icons/compensations-and-benefits.png'),
	notification: require('../Images/Icons/notification.png'),

	homeActive: require('../Images/Icons/home-active.png'),
	contactsActive: require('../Images/Icons/contacts-active.png'),
	compensationsAndBenefitsActive: require('../Images/Icons/compensations-and-benefits-active.png'),
	notificationActive: require('../Images/Icons/notification-active.png'),

	// personalRelations: require('Images/Icons/personal-relations.png'),
	// pastWorkingProcess: require('Images/Icons/past-working-process.png'),
	// currentWorkingProcess: require('Images/Icons/current-working-process.png'),
	// workingContract: require('Images/Icons/working-contract.png'),
	// educationalProcess: require('Images/Icons/educational-process.png'),
	// KpiProcess: require('Images/Icons/kpi.png'),
	// allowanceRecordsProcess: require('Images/Icons/allowance-records-process.png'),
	// rewardsProcess: require('Images/Icons/rewards-process.png'),
	// disciplinaryProcess: require('Images/Icons/disciplinary-process.png'),
	// settings: require('Images/Icons/settings.png'),
	// switchCompany: require('Images/Icons/switch-company.png'),

	// approveReason: require('Images/Icons/approve-reason.png'),

	// processAddress: require('Images/Icons/process-address.png'),
	// processCalendar: require('Images/Icons/process-calendar.png'),
	// processPhone: require('Images/Icons/process-phone.png'),
	// processCompany: require('Images/Icons/process-company.png'),
	// processPosition: require('Images/Icons/process-position.png'),
	// processReason: require('Images/Icons/process-reason.png'),
	// processSalary: require('Images/Icons/process-salary.png'),
	// processStatus: require('Images/Icons/process-status.png'),
	// processDepartment: require('Images/Icons/process-department.png'),
	// processClipboardAccount: require('Images/Icons/process-clipboard-account.png'),
	// processNameCode: require('Images/Icons/process-name-code.png'),
	// processNameCodeOutlined: require('Images/Icons/process-name-code-2.png'),
	// processUser: require('Images/Icons/process-user.png'),
	// processUserOutlined: require('Images/Icons/process-user-2.png'),
	// processNameEng: require('Images/Icons/process-name-eng.png'),
	// processManager: require('Images/Icons/process-manager.png'),
	// processApprovalManager: require('Images/Icons/process-approval-manager.png'),
	// processThreeTierPyramid: require('Images/Icons/process-three-tier-pyramid.png'),
	// processPersonalMail: require('Images/Icons/process-personal-mail.png'),
	// processWorkPlaceAccount: require('Images/Icons/process-workplace-account.png'),
	// processLoyalty: require('Images/Icons/process-loyalty.png'),
	// processHealthInsurance: require('Images/Icons/process-health-insurance.png'),
	// processEmergencyCall: require('Images/Icons/process-emergency-call.png'),
	// processEmergencyContactRelationship: require('Images/Icons/process-emergency-contact-relationship.png'),
	// processSigningUser: require('Images/Icons/process-signing-user.png'),
	// processContract: require('Images/Icons/process-contract.png'),
	// processTime: require('Images/Icons/process-time.png'),
	// processCertificate: require('Images/Icons/process-certificate.png'),
	// processGraduation: require('Images/Icons/process-graduation.png'),
	// processMajor: require('Images/Icons/process-major.png'),
	// processResult: require('Images/Icons/process-result.png'),
	// processSchool: require('Images/Icons/process-school.png'),
	// processCreditCard: require('Images/Icons/process-credit-card.png'),
	// processTax: require('Images/Icons/process-tax.png'),
	// processBank: require('Images/Icons/process-bank.png'),
	// processBankBuilding: require('Images/Icons/process-bank-building.png'),
	// processHealth: require('Images/Icons/process-health.png'),
	// processBlood: require('Images/Icons/process-blood.png'),
	// processNote: require('Images/Icons/process-note.png'),
	// processBirthday: require('Images/Icons/process-birthday.png'),
	// processRelation: require('Images/Icons/process-relation.png'),
	// processReduce: require('Images/Icons/process-reduce.png'),
	// processGender: require('Images/Icons/process-gender.png'),
	// processId: require('Images/Icons/process-id.png'),
	// processNationality: require('Images/Icons/process-nationality.png'),
	// processEmail: require('Images/Icons/process-email.png'),
	// processResolutionNumber: require('Images/Icons/process-resolution-number.png'),
	// processPercentage: require('Images/Icons/process-percentage.png'),
	// processPayment: require('Images/Icons/process-payment.png'),
	// processMoneyBag: require('Images/Icons/process-money-bag.png'),
	// processGasStation: require('Images/Icons/process-gas-station.png'),
	// processGasoline: require('Images/Icons/process-gasoline.png'),
	// processDecision: require('Images/Icons/process-decision.png'),
	// processWinner: require('Images/Icons/process-winner.png'),
	// processProfit: require('Images/Icons/process-profit.png'),
	// processFeedback: require('Images/Icons/process-feedback.png'),
	// processStamp: require('Images/Icons/process-stamp.png'),
	// processTimer: require('Images/Icons/process-timer.png'),
	// processExplanation: require('Images/Icons/process-explanation.png'),
	// processStopwatch: require('Images/Icons/process-stopwatch.png'),
	// processList: require('Images/Icons/process-list.png'),
	// processLevels: require('Images/Icons/process-levels.png'),
	// processDiscipline: require('Images/Icons/process-discipline.png'),
	// processMoney: require('Images/Icons/process-money.png'),
	// processReward: require('Images/Icons/process-reward.png'),
	// processRewardLevel: require('Images/Icons/process-reward-level.png'),
	// processMoneyDecision: require('Images/Icons/process-money-decision.png'),
	// processMoneyPercentage: require('Images/Icons/process-money-percentage.png'),
	// processGas: require('Images/Icons/process-gas.png'),
	// processTotalMoney: require('Images/Icons/process-total-money.png'),
	// processGasMoney: require('Images/Icons/process-gas-money.png'),
	// processExtraMoney: require('Images/Icons/process-extra-money.png'),
	// processIn: require('Images/Icons/process-in.png'),
	// processOut: require('Images/Icons/process-out.png'),
	// processReasonOutline: require('Images/Icons/process-reason-outline.png'),
	// processStatusOutline: require('Images/Icons/process-status-outline.png'),
	// processCross: require('Images/Icons/process-cross.png'),
	// processSetting: require('Images/Icons/process-setting.png'),
	// settingsChangePassword: require('Images/Icons/settings-change-password.png'),
	// processMajorLevel: require('Images/Icons/process-major-level.png'),
	// processUserLock: require('Images/Icons/process-user-lock.png'),
	// processTitle: require('Images/Icons/process-title.png'),
	// processReview: require('Images/Icons/process-review.png'),
	// processTrainingForm: require('Images/Icons/process-training-form.png'),
	// processRewardContent: require('Images/Icons/process-reward-content.png'),
	// processGraph: require('Images/Icons/process-graph.png'),
	// processCalandarGraph: require('Images/Icons/process-calendar-graph.png'),
	// processMoneyStack: require('Images/Icons/process-money-stack.png'),
	// processClassification: require('Images/Icons/process-classification.png'),
	// processCoinStack: require('Images/Icons/process-coin-stack.png'),
	// processDollarArrow: require('Images/Icons/process-dollar-arrow.png'),
	// processUserContract: require('Images/Icons/process-user-contract.png'),
	// processCoinStackArrow: require('Images/Icons/process-coin-stack-arrow.png'),
	// processDollarChart: require('Images/Icons/process-dollar-chart.png'),
	// processUserArrow: require('Images/Icons/process-user-arrow.png'),
	// processDollarBag: require('Images/Icons/process-dollar-bag.png'),
	// processDollarBulb: require('Images/Icons/process-dollar-bulb.png'),
	// processDollarHazard: require('Images/Icons/process-dollar-hazard.png'),
	// processDollarPhone: require('Images/Icons/process-dollar-phone.png'),
	// processFireShield: require('Images/Icons/process-fire-shield.png'),
	// processPresentation: require('Images/Icons/process-presentation.png'),
	// pendingStep: require('Images/Icons/pending-step.png'),
	// cardName: require('Images/Icons/card-name.png'),
	// qrCode: require('Images/Icons/qr-code.png'),
	iconFaceID: require('../Images/Icons/icon-faceID.png'),
	// faceIDIDP: require('Images/Icons/faceIDIDP.png'),
	// faceIDTLSG: require('Images/Icons/faceIDTLSG.png'),
	// faceIDBCG: require('Images/Icons/faceIDBCG.png'),
	gpsCheckIn: require('../Images/Icons/gps-check-in.png'),
	wifiCheckIn: require('../Images/Icons/wifi-check-in.png'),
	crossClose: require('../Images/Icons/cross-close.png'),
	iconReport: require('../Images/Icons/icon-report.png'),
	// iconMenuBar: require('Images/Icons/icon-menu-bar.png'),

	// logout: require('Images/Icons/logout.png'),

	// itemRightChevron: require('Images/Icons/item-right-chevron.png'),
	// iconBellDashboard: require('Images/Icons/bell-dashbload.png'),

	calendar: require('../Images/Icons/calendar.png'),
	// calendarClean: require('Images/Icons/calendar-clean.png'),
	// approveManager: require('Images/Icons/approve-manager.png'),
	// notes: require('Images/Icons/notes.png'),
	// registerRemark: require('Images/Icons/register-remark.png'),
	// timesheetExplanation: require('Images/Icons/timesheet-explanation.png'),
	// approveTimeExplanation: require('Images/Icons/approve-time-explanation.png'),
	// registerLunchSkip: require('Images/Icons/register-launch-leave.png'),

	// statusPending: require('Images/Icons/status-pending.png'),
	// statusApproved: require('Images/Icons/status-approved.png'),
	// statusRejected: require('Images/Icons/status-rejected.png'),
	// statusCreated: require('Images/Icons/status-created.png'),

	// recordType: require('Images/Icons/record-type.png'),
	// rejectReason: require('Images/Icons/reject-reason.png'),

	// typeList: require('Images/Icons/list.png'),
	// remark: require('Images/Icons/remark.png'),
	// clock: require('Images/Icons/clock.png'),

	// logoUShop: require('Images/Icons/u-shop.png'),
	// logoJupviec: require('Images/Icons/jup-viec.png'),
	// logoGrapFinance: require('Images/Icons/grap-finance.png'),
	// logoGotadi: require('Images/Icons/gotadi.png'),
	// logoBaoViet: require('Images/Icons/bao-viet.png'),
	// logoMSIG: require('Images/Icons/msig.png'),
	// logoMSIGLarge: require('Images/Icons/msig-large.png'),
	// logoLargeUShop: require('Images/Icons/u-shop-large.png'),
	// logoLargeJupviec: require('Images/Icons/jup-viec-large.png'),
	// logoLargeGotadi: require('Images/Icons/gotadi-large.png'),
	// logoLargeMSIG: require('Images/Icons/msigicon-large.png'),

	// badgeNew: require('Images/Icons/badge-new.png'),
	// tagHot: require('Images/Icons/tag-hot.png'),

	// tempPromotion1: require('Images/tempPromotion1.png'),
	// tempPromotion2: require('Images/tempPromotion2.png'),
	// tempPromotion3: require('Images/tempPromotion3.png'),
	// tempPromotion4: require('Images/tempPromotion4.png'),

	// compensationsAndBenefitsBenefits: require('Images/Icons/compensations-and-benefits-benefits.png'),
	// compensationsAndBenefitsBusinessSalary: require('Images/Icons/compensations-and-benefits-business-salary.png'),
	// compensationsAndBenefitsSalary: require('Images/Icons/compensations-and-benefits-salary.png'),
	// compensationsAndBenefitsInsurance: require('Images/Icons/compensations-and-benefits-insurance.png'),
	// compensationsAndBenefitsTransportation: require('Images/Icons/compensations-and-benefits-transportation.png'),
	// compensationsAndBenefitsHousing: require('Images/Icons/compensations-and-benefits-housing.png'),

	// insuranceSocial: require('Images/Icons/insurance-social.png'),
	// insuranceMedical: require('Images/Icons/insurance-medical.png'),
	// insuranceUnemployment: require('Images/Icons/insurance-unemployment.png'),
	// insuranceHealth: require('Images/Icons/insurance-health.png'),

	// figureForgotPassword: require('Images/figure-forgot-password.png'),
	// figureChangePassword: require('Images/figure-change-password.png'),

	// // KVP
	// //------------------------
	// kvpParentalLeave: require('Images/Icons/kvp-parental-leave.png'),
	// kvpBook: require('Images/Icons/book.png'),

	// kvpLateInEarlyOutBenefit: require('Images/Icons/kvp-late-in-early-out-benefit.png'),
	// kvpChildBenefit: require('Images/Icons/kvp-child-benefit.png'),
	// kvpShiftWork: require('Images/Icons/kvp-shift-work.png'),

	// // MAVIN
	// // -----------------------
	// employeePayment: require('Images/Icons/employee-payment.png'),
	// speaker: require('Images/Icons/speaker.png'),
	// shift: require('Images/Icons/shift.png'),
	// workPreShift: require('Images/Icons/work-pre-shift.png'),
	// noPreShiftWork: require('Images/Icons/no-pre-shift-work.png'),
	// compensatoryLeave: require('Images/Icons/compensatory-leave.png'),
	// noCompensatoryLeave: require('Images/Icons/no-compensatory-leave.png'),

	// logoHSV: require('Images/logohsv.png'),
	// WifiTimeclock: require('Images/Icons/wifi.png'),
	// backgroundhsv: require('Images/bghsv.png'),
	// logohistaff_1: require('Images/logohistaff.png'),

	// backgroundidp: require('Images/backgroundidp.png'),
	// logoidp: require('Images/logoIDP.png'),

	// backgroundtlsg: require('Images/backgroundTLSG.png'),
	// logotlsg: require('Images/logoTLSG.png'),

	// chevronRight2: require('Images/Icons/chevronright.png'),
	// chevronDown: require('Images/Icons/chevron-down.png'),

	// // uncheck: require('Images/Icons/uncheck.png'),
	// // check: require('Images/Icons/check.png'),
	// //IDP
	// NotifiDetailEvent: require('Images/NotifiDetailEvent.png'),
	// NotifiEvent: require('Images/NotifiEvent.png'),
	// canlender_time: require('Images/Icons/canlender_time.png'),
	// Location_time: require('Images/Icons/Location.png'),
	// bachgroud_InfoOfInterest: require('Images/bachgroud_InfoOfInterests.png'),
	// iconPopupFace: require('Images/Icons/iconPopupFace.png'),
	// wifiicon: require('Images/Icons/Wifiicon.png'),
	// zalo: require('Images/Icons/zalo.png'),
	// WifiNotConnect: require('Images/Icons/WifiNotConnect.png'),
	// AttendanceData: require('Images/Icons/IconAttendanceData.png'),
	// iconFace_ID: require('Images/Icons/iconFaceID.png'),
	// ViewCV: require('Images/Icons/ViewCV.png'),
	// AppVui: require('Images/Icons/AppVui.png'),
	// EmpCVIcon: require('Images/Icons/imgpsh_fullsize_anim.png'),
	// //bcg
	// capbacBCGicon: require('Images/Icons/capbacicon.png'),
	// noilamviecBCGicon: require('Images/Icons/noilamviecicon.png'),
	// longcophieuBCGicon: require('Images/Icons/longcophieuicon.png'),
	// congtyBCGicon: require('Images/Icons/congtyicon.png'),
	// thamnienBCGicon: require('Images/Icons/thamnienicon.png'),

	// HoidongIcon: require('Images/Icons/HoidongIcon.png'),
	// KiemnhiemIcon: require('Images/Icons/KiemnhiemIcon.png'),
	// KyluatIcon: require('Images/Icons/KyluatIcon.png'),
	// KhenthuongIcon: require('Images/Icons/KhenthuongIcon.png'),

	// backgroundbcg: require('Images/backgroundBCG.png'),
	// logobcg: require('Images/logoBCG.png'),
	// addcontact: require('Images/Icons/addcontact.png'),
	// SendMail: require('Images/Icons/SendMail.png'),

	// imgCMNDs: require('Images/imgCMND.png'),
};

export default images;
