const light = {
    primary: '#FF773E',
    primarySecondary: '#FFEED4',
    text: {
        placeholder: '##A7A7A7',
        input: '#464646',
        icon: '#FF773E',
        normal: '#71a',
        require: '#FF1212',
        header: '#FFFFFF',
        warning: '#FF1212',
        buttonPrimary: '#FFFFFF',
        buttonNormal: '#FF773E',
        badge: '#FFFFFF',
        leave: '#FF773E',
        off: '#FF773E',
        approve: '#FF773E',
        title: '#464646',
    },
    background: {
        primary: '#FFFFFF',
        screen: '#F5F5F5',
        buttomDashboard: '#FCF5E3',
        icon: '#F5F5F5',
        background: '#0000001A',
        modal: '#A1A1A2AA',
        badge: '#FF1212',
    },
    icon: {
        primary: '#FF773E',
        normal: '#A7A7A7',
    },
    button: {
        primary: '#616163',
        normal: '#FFFFFF',
        warning: '#FF773E',
        cancle: '#FF1212',
        Dashboard: '#FCF5E3',
        iconHome: '#FFFFFF',
        loading: '#A1A1A2',
        approve: '#A1A1A2',
    },
    chart: {
        chart1: '#FF8D5D',
        chart2: '#FECB7F',
        chart3: '#D6ED8B',
        chart4: '#D2D2D2',
        chart5: '#B8DEAB',
        chart6: '#B4D8F3',
        chart7: '#D2D2D2',
        chart8: '#FFD952',
    },
    radio: {
        primary: '#FFD952',
    },
    Indicator: '#FFFFFF',
    border: '#D6D6D6',
}

export default light;